In [1]:
import numpy as np

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [4]:
 np.ones((3, 4, 5), dtype=np.float64).strides 

(160, 40, 8)

In [6]:
ints = np.ones(10, dtype=np.uint16)
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [7]:
np.issubdtype(ints.dtype, np.integer) 

True

In [8]:
arr = np.arange(15).reshape((5, 3))


In [9]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [12]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#The flatten method behaves like ravel except it always returns a copy of the data: In [27]: 
arr.flatten() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr = np.arange(12).reshape((3, 4))
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

There are two special objects in the NumPy namespace, r_ and c_, that make stacking arrays more concise

In [15]:
arr = np.arange(6)


In [17]:
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)


In [19]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.34831669, -0.41776642],
       [-1.86877449, -0.45634478],
       [-0.04030894, -0.31354178]])

In [20]:
np.c_[np.r_[arr1, arr2], arr] 

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.34831669, -0.41776642,  3.        ],
       [-1.86877449, -0.45634478,  4.        ],
       [-0.04030894, -0.31354178,  5.        ]])

In [21]:
np.c_[1:6, -10:-5] 

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [26]:
a=np.arange(3)
b=a.repeat(3)
b

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [30]:
c=b.repeat(3,axis=0)
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [33]:
arr = np.random.randn(2, 2)
arr.repeat(3,axis=1)


array([[-1.57364232, -1.57364232, -1.57364232, -0.86653051, -0.86653051,
        -0.86653051],
       [ 0.12697868,  0.12697868,  0.12697868,  0.04727671,  0.04727671,
         0.04727671]])

In [34]:
arr.repeat(3,axis=0)

array([[-1.57364232, -0.86653051],
       [-1.57364232, -0.86653051],
       [-1.57364232, -0.86653051],
       [ 0.12697868,  0.04727671],
       [ 0.12697868,  0.04727671],
       [ 0.12697868,  0.04727671]])

In [36]:
arr.repeat([2, 3], axis=0)

array([[-1.57364232, -0.86653051],
       [-1.57364232, -0.86653051],
       [ 0.12697868,  0.04727671],
       [ 0.12697868,  0.04727671],
       [ 0.12697868,  0.04727671]])

In [37]:
#fancy indexing
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [38]:
inds = [7, 1, 2, 6] 
arr[inds]

array([700, 100, 200, 600])

In [40]:
arr.take(inds)

array([700, 100, 200, 600])

In [42]:
arr.put(inds, 42)  #replace


In [43]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [44]:
arr.put(inds, [40, 41, 42, 43])


In [45]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

**Broadcasting**
#*Broadcasting describes how arithmetic works between arrays of different shapes. 
#
#*It is a very powerful feature, but one that can be easily misunderstood, even by experienced users

In [46]:
arr = np.arange(5)
arr*4

array([ 0,  4,  8, 12, 16])

In [53]:
arr = np.random.randn(4, 3)
arr.shape

(4, 3)

In [51]:
m_0=arr.mean(0)
m_0

array([0.19651421, 0.55512751, 0.23198715])

In [52]:
arr-m_0

array([[-0.57768484,  0.88695277, -0.44897326],
       [ 0.3868148 , -0.05859454, -0.64257943],
       [ 1.10253708, -1.51993306,  0.47813261],
       [-0.91166703,  0.69157483,  0.61342008]])

In [55]:
m_1=arr.mean(1)
m_1

array([0.44840271, 0.34835676, 0.2376907 , 0.33567896])

In [59]:
arr-m_1.reshape(4,1)

array([[ 1.0841075 , -0.833699  , -0.2504085 ],
       [ 0.48824865,  0.13170138, -0.61995003],
       [-0.76873629,  0.12114912,  0.64758717],
       [ 0.09245921, -0.21678309,  0.12432387]])

In [64]:
arr = np.random.randn(6)
arr

array([-0.72588808,  0.570595  ,  1.04779525, -0.92943381, -0.78774828,
        0.3951038 ])

In [66]:
arr.sort()
arr

array([-0.92943381, -0.78774828, -0.72588808,  0.3951038 ,  0.570595  ,
        1.04779525])

In [67]:
arr=np.random.randn(4,3)

In [68]:
arr.sort(axis=1)


In [69]:
arr

array([[-1.07079446, -0.215041  , -0.18108721],
       [-1.16339405, -0.39233287,  0.56664888],
       [-1.74169909, -0.48492521,  0.74145201],
       [-1.59044948, -0.6331882 , -0.31060343]])

In [70]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort() #gives index of sorted array


In [73]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [75]:
values[indexer]

array([0, 1, 2, 3, 5])

In [77]:
arr[0].argsort()

array([0, 1, 2], dtype=int64)

In [78]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))


In [80]:
zip(last_name[sorter], first_name[sorter])

In [82]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)] 
for a, b, c in seq:    
    
    pass 